In [1]:
### Importando bibliotecas

import pandas as pd

In [9]:
### Lendo arquivo e renomeando colunas

filename = 'K3241.K03200Y9.D30211.ESTABELE.csv'
columns = ['CNPJ BÁSICO',
           'CNPJ ORDEM ',
           'CNPJ DV',
           'IDENTIFICADOR MATRIZ/FILIAL',
           'NOME FANTASIA',
           'SITUAÇÃO CADASTRAL',
           'DATA SITUAÇÃO CADASTRAL',
           'MOTIVO SITUAÇÃO CADASTRAL',
           'NOME DA CIDADE NO EXTERIOR',
           'PAIS',
           'DATA DE INÍCIO ATIVIDADE ',
           'CNAE FISCAL PRINCIPAL',
           'CNAE FISCAL SECUNDÁRIA',
           'TIPO DE LOGRADOURO',
           'LOGRADOURO',
           'NÚMERO',
           'COMPLEMENTO',
           'BAIRRO',
           'CEP ',
           'UF',
           'MUNICÍPIO',
           'DDD 1 ',
           'TELEFONE 1',
           'DDD 2',
           'TELEFONE 2',
           'DDD DO FAX',
           'FAX ',
           'CORREIO ELETRÔNICO',
           'SITUAÇÃO ESPECIAL',
           'DATA DA SITUAÇÃO ESPECIAL']
df = pd.read_csv(filename, sep=';', names = columns, encoding='latin-1')

C:\Users\levim\AppData\Local\Temp\ipykernel_12204\1859180746.py:32: DtypeWarning: Columns (8,21,22,24,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename, sep=';', names = columns, encoding='latin-1')

In [36]:
df.shape

(4753435, 32)

In [16]:
df.sample(10)

,CNPJ BÁSICO,CNPJ ORDEM,CNPJ DV,IDENTIFICADOR MATRIZ/FILIAL,NOME FANTASIA,SITUAÇÃO CADASTRAL,DATA SITUAÇÃO CADASTRAL,MOTIVO SITUAÇÃO CADASTRAL,NOME DA CIDADE NO EXTERIOR,PAIS,...,DDD 1,TELEFONE 1,DDD 2,TELEFONE 2,DDD DO FAX,FAX,CORREIO ELETRÔNICO,SITUAÇÃO ESPECIAL,DATA DA SITUAÇÃO ESPECIAL,CNPJ COMPLETO
3703737,22158052,1,23,1,BAR RESTAURANTE E MERCEARIA DO SOM,2,20150330,0,NaN,NaN,...,31.0,34216301.0,NaN,NaN,NaN,NaN,JOVAIRGOMES@YAHOO.COM.BR,NaN,NaN,22158052123
727395,48541057,1,24,1,OITO SCP - 33,2,20211112,0,NaN,NaN,...,11.0,37914542.0,NaN,NaN,NaN,NaN,CONTATO@PPSE.COM.BR,NaN,NaN,48541057124
2626221,9730693,1,42,1,NaN,8,20081231,1,NaN,NaN,...,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,9730693142
2003245,7369685,27,26,2,COMERCIAL GERDAU,8,20130328,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73696852726
316384,44074196,1,34,1,EDSON ISTALADOR DE ANTENAS,2,20211029,0,NaN,NaN,...,35.0,99909346.0,NaN,NaN,NaN,NaN,EDSONMACIEL23@YAHOO.COM.BR,NaN,NaN,44074196134
3916751,24688268,1,26,1,VISUALCOR,2,20160428,0,NaN,NaN,...,71.0,35079008.0,71.0,35079025.0,NaN,NaN,NILTON@VISUALCOR.COM.BR,NaN,NaN,24688268126
3635256,21321516,1,8,1,VR LOCACOES,2,20141031,0,NaN,NaN,...,49.0,91070504.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2132151618
850821,5016783,1,15,1,APARAS GUARANI,4,20210119,63,NaN,NaN,...,12.0,39237448,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5016783115
4730792,32407895,1,70,1,KARINA ELIANA MILLEO DE OLIVEIRA,4,20220607,63,NaN,NaN,...,41.0,99335103.0,NaN,NaN,NaN,NaN,MILLEOGERONAZZO@GMAIL.COM,NaN,NaN,32407895170
662238,47852208,1,0,1,NaN,2,20220906,0,NaN,105.0,...,83.0,31136008.0,0.0,0.0,NaN,NaN,ALLIANCECONTABILIDADEPB@GMAIL.COM,NaN,NaN,4785220810

In [41]:
### Criando colunas CNPJ COMPLETO e TELEFONE

df['CNPJ COMPLETO'] = df['CNPJ BÁSICO'].astype(str) + df['CNPJ ORDEM '].astype(str) + df['CNPJ DV'].astype(str)
df['TELEFONE'] = df['DDD 1 '].astype(str) + df['TELEFONE 1'].astype(str)


### Criando pivot_table apenas com as colunas que serão utilizadas

registros = df.pivot_table(
    index='CNPJ COMPLETO',
    values=['NOME FANTASIA', 'CEP ', 'TELEFONE', 'CORREIO ELETRÔNICO'],
    aggfunc='first'
)
registros.sample(10)

,CEP,CORREIO ELETRÔNICO,NOME FANTASIA,TELEFONE
CNPJ COMPLETO,,,,
3264410813,55590000.0,RICARDOFELIX7663@GMAIL.COM,FRIGORIFICO ARCO-IRIS,81.035591173.0
45889365157,5874180.0,ESTERHONORIOSANTOS86398@GMAIL.COM,EXPRESSO PATINHAS,11.060569635.0
25936718115,57925000.0,FABIANEGORETT@HOTMAIL.COM,None,0.00
7263722188,20011030.0,None,None,21.025245881
57926347187,6434140.0,None,None,nannan
46073368180,20710180.0,MARCODOSS@GMAIL.COM,ARTSAFE CORRETOR DE SEGUROS,21.064796788.0
30496274184,59122241.0,CARNEIROCONSTRUCOES@OUTLOOK.COM,CARNEIRO CONSTRUCOES,84.087597829.0
44516489124,31340290.0,CONTATODRIELLEFONSECA@GMAIL.COM,None,31.097306787.0
4642469185,70863520.0,None,ELETROS OUT LET,61.033283320
10798635130,57014550.0,None,CHRYS MODAS,nannan

In [45]:
### Salvando arquivo em csv com apenas 10 registros

registros.sample(10).to_csv('estabelecimentos10.csv')

In [46]:
### Importando bibliotecas para conexão com o MongoDB

import pymongo
import json

In [59]:
### Transformando arquivo csv em json

df = pd.read_csv('estabelecimentos10.csv')
data = df.to_dict(orient = "records")
data

[{'CNPJ COMPLETO': 15865258128,
  'CEP ': 29125350.0,
  'CORREIO ELETRÔNICO': 'AILTOVARGAS@HOTMAIL.COM',
  'NOME FANTASIA': 'PSOL - DIRETORIO MUNICIPAL DE VILA VELHA',
  'TELEFONE': '27.098803100.0'},
 {'CNPJ COMPLETO': 5061405614,
  'CEP ': 1453010.0,
  'CORREIO ELETRÔNICO': nan,
  'NOME FANTASIA': nan,
  'TELEFONE': 'nannan'},
 {'CNPJ COMPLETO': 44715099183,
  'CEP ': 45638000.0,
  'CORREIO ELETRÔNICO': 'CLEITONSANTANA836@GMAIL.COM',
  'NOME FANTASIA': 'DOM BARBUDO',
  'TELEFONE': '73.081430711.0'},
 {'CNPJ COMPLETO': 6749463137,
  'CEP ': 60150161.0,
  'CORREIO ELETRÔNICO': nan,
  'NOME FANTASIA': 'ECONTELL',
  'TELEFONE': '85.04639419'},
 {'CNPJ COMPLETO': 95250569111,
  'CEP ': 93336001.0,
  'CORREIO ELETRÔNICO': nan,
  'NOME FANTASIA': 'ELEBEEFE COMERCIO E REPRESENTACOES',
  'TELEFONE': 'nannan'},
 {'CNPJ COMPLETO': 12633518141,
  'CEP ': 19806705.0,
  'CORREIO ELETRÔNICO': 'WALDSONTEODORO@YHAOO.COM.BR',
  'NOME FANTASIA': nan,
  'TELEFONE': '18.033211583.0'},
 {'CNPJ COMPLETO': 31487763132,
  'CEP ': 28800000.0,
  'CORREIO ELETRÔNICO': 'GRUPORESOLVE@OI.COM.BR',
  'NOME FANTASIA': 'DISTRIBUIDORA DE CIMENTO SAO JORGE',
  'TELEFONE': '22.026305639.0'},
 {'CNPJ COMPLETO': 25808462160,
  'CEP ': 78200000.0,
  'CORREIO ELETRÔNICO': 'coligacaottr@gmail.com',
  'NOME FANTASIA': nan,
  'TELEFONE': '0.00'},
 {'CNPJ COMPLETO': 1100152810,
  'CEP ': 11740000.0,
  'CORREIO ELETRÔNICO': 'CONTABILTEIXEIRA@HOTMAIL.COM',
  'NOME FANTASIA': 'FEMININA DESING',
  'TELEFONE': '13.034276203.0'},
 {'CNPJ COMPLETO': 27909897127,
  'CEP ': 91750660.0,
  'CORREIO ELETRÔNICO': 'sergiiolewis@gmail.com',
  'NOME FANTASIA': 'FUNILARIA NUNES',
  'TELEFONE': '51.093902695.0'}]

In [60]:
### Conectando ao MongoDB

client = pymongo.MongoClient('mongodb://mongoadmin:password@localhost:27017/')
db = client['estabelecimentos']
print(db)

Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'estabelecimentos')

In [57]:
### Inserindo dados no MongoDB

db.dados.insert_many(data)