# Python

In [1]:
### Importando bibliotecas

import pandas as pd

In [2]:
### Lendo arquivo e renomeando colunas

filename = 'K3241.K03200Y9.D30211.ESTABELE.csv'
columns = ['CNPJ BÁSICO',
           'CNPJ ORDEM ',
           'CNPJ DV',
           'IDENTIFICADOR MATRIZ/FILIAL',
           'NOME FANTASIA',
           'SITUAÇÃO CADASTRAL',
           'DATA SITUAÇÃO CADASTRAL',
           'MOTIVO SITUAÇÃO CADASTRAL',
           'NOME DA CIDADE NO EXTERIOR',
           'PAIS',
           'DATA DE INÍCIO ATIVIDADE ',
           'CNAE FISCAL PRINCIPAL',
           'CNAE FISCAL SECUNDÁRIA',
           'TIPO DE LOGRADOURO',
           'LOGRADOURO',
           'NÚMERO',
           'COMPLEMENTO',
           'BAIRRO',
           'CEP ',
           'UF',
           'MUNICÍPIO',
           'DDD 1 ',
           'TELEFONE 1',
           'DDD 2',
           'TELEFONE 2',
           'DDD DO FAX',
           'FAX ',
           'CORREIO ELETRÔNICO',
           'SITUAÇÃO ESPECIAL',
           'DATA DA SITUAÇÃO ESPECIAL']
df = pd.read_csv(filename, sep=';', names = columns, encoding='latin-1')

C:\Users\lgmot\AppData\Local\Temp\ipykernel_27180\52663161.py:34: DtypeWarning: Columns (8,21,22,24,26,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename, sep=';', names = columns, encoding='latin-1')

In [3]:
### Vendo numero de linhas e colunas

df.shape

(4753435, 30)

In [4]:
### Criando colunas CNPJ COMPLETO e TELEFONE

df['CNPJ COMPLETO'] = df['CNPJ BÁSICO'].astype(str) + df['CNPJ ORDEM '].astype(str) + df['CNPJ DV'].astype(str)
df['TELEFONE'] = df['DDD 1 '].astype(str) + df['TELEFONE 1'].astype(str)

In [5]:
### separado colunas

dfreg = df.sample(10)
dfreg.sample(10)

,CNPJ BÁSICO,CNPJ ORDEM,CNPJ DV,IDENTIFICADOR MATRIZ/FILIAL,NOME FANTASIA,SITUAÇÃO CADASTRAL,DATA SITUAÇÃO CADASTRAL,MOTIVO SITUAÇÃO CADASTRAL,NOME DA CIDADE NO EXTERIOR,PAIS,...,TELEFONE 1,DDD 2,TELEFONE 2,DDD DO FAX,FAX,CORREIO ELETRÔNICO,SITUAÇÃO ESPECIAL,DATA DA SITUAÇÃO ESPECIAL,CNPJ COMPLETO,TELEFONE
1657321,7305415,1,12,1,BOMBONIERE NOSSA SENHORA DE FATIMA,8,20150209,73,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7305415112,nannan
3637864,21353382,1,7,1,IOIO MODA FEMININA PLUS SIZE,8,20180201,67,NaN,NaN,...,99016151.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2135338217,31.099016151.0
3819545,23552968,1,26,1,AILUS,4,20210210,63,NaN,NaN,...,96848374.0,NaN,NaN,NaN,NaN,suzana.goncalves07@gmail.com,NaN,NaN,23552968126,61.096848374.0
2572721,20228531,1,43,1,ALSACIA,2,20140321,0,NaN,NaN,...,33620739.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20228531143,61.033620739.0
194315,43205486,1,7,1,JACOBINA 24 HORAS,2,20210820,0,NaN,NaN,...,99125102.0,NaN,NaN,NaN,NaN,ECARVALHO936@GMAIL.COM,NaN,NaN,4320548617,74.099125102.0
4364432,28086356,1,9,1,LIMA TRANSPORTES,2,20170703,0,NaN,NaN,...,81356928.0,NaN,NaN,NaN,NaN,wellingtonbrandao_@hotmail.com,NaN,NaN,2808635619,17.081356928.0
1769967,28128189,1,11,1,BELTEC,8,19660819,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28128189111,nannan
92958,42149739,1,0,1,FRANCO REPRESENTACOES,2,20210531,0,NaN,NaN,...,99287610.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4214973910,45.099287610.0
3453889,18884972,1,51,1,URBAN SERVICE,2,20130916,0,NaN,NaN,...,26352295.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18884972151,21.026352295.0
821107,49527508,1,31,1,BODY FITNESS COMERCIO DE SUPLEMENTOS E ROUPAS,2,20230208,0,NaN,NaN,...,99364293,NaN,NaN,NaN,NaN,MONIA.ABRAO@GMAIL.COM,NaN,NaN,49527508131,34.099364293

In [7]:
### Criando pivot_table apenas com as colunas que serão utilizadas

registros = dfreg.pivot_table(
    index='CNPJ COMPLETO',
    values=['NOME FANTASIA', 'CEP ', 'TELEFONE', 'CORREIO ELETRÔNICO'],
    aggfunc='first'
)
registros.sample(10)

,CEP,CORREIO ELETRÔNICO,NOME FANTASIA,TELEFONE
CNPJ COMPLETO,,,,
2135338217,30580002.0,None,IOIO MODA FEMININA PLUS SIZE,31.099016151.0
4320548617,44700000.0,ECARVALHO936@GMAIL.COM,JACOBINA 24 HORAS,74.099125102.0
49527508131,38400748.0,MONIA.ABRAO@GMAIL.COM,BODY FITNESS COMERCIO DE SUPLEMENTOS E ROUPAS,34.099364293
23552968126,73105903.0,suzana.goncalves07@gmail.com,AILUS,61.096848374.0
2808635619,15110000.0,wellingtonbrandao_@hotmail.com,LIMA TRANSPORTES,17.081356928.0
7305415112,55155720.0,None,BOMBONIERE NOSSA SENHORA DE FATIMA,nannan
20228531143,71215222.0,None,ALSACIA,61.033620739.0
28128189111,29017020.0,None,BELTEC,nannan
18884972151,24800037.0,None,URBAN SERVICE,21.026352295.0
4214973910,85909227.0,None,FRANCO REPRESENTACOES,45.099287610.0

In [8]:
### Salvando arquivo em csv com apenas 10 registros

registros.sample(10).to_csv('estabelecimentos10.csv')

In [25]:
### Transformando arquivo csv em json

df = pd.read_csv('estabelecimentos10.csv')
df = df.fillna('None')
estabelecimentos_data = df.to_dict(orient = "records")
estabelecimentos_data

[{'CNPJ COMPLETO': 23552968126,
  'CEP ': 73105903.0,
  'CORREIO ELETRÔNICO': 'suzana.goncalves07@gmail.com',
  'NOME FANTASIA': 'AILUS',
  'TELEFONE': '61.096848374.0'},
 {'CNPJ COMPLETO': 7305415112,
  'CEP ': 55155720.0,
  'CORREIO ELETRÔNICO': 'None',
  'NOME FANTASIA': 'BOMBONIERE NOSSA SENHORA DE FATIMA',
  'TELEFONE': 'nannan'},
 {'CNPJ COMPLETO': 4214973910,
  'CEP ': 85909227.0,
  'CORREIO ELETRÔNICO': 'None',
  'NOME FANTASIA': 'FRANCO REPRESENTACOES',
  'TELEFONE': '45.099287610.0'},
 {'CNPJ COMPLETO': 49527508131,
  'CEP ': 38400748.0,
  'CORREIO ELETRÔNICO': 'MONIA.ABRAO@GMAIL.COM',
  'NOME FANTASIA': 'BODY FITNESS COMERCIO DE SUPLEMENTOS E ROUPAS',
  'TELEFONE': '34.099364293'},
 {'CNPJ COMPLETO': 4320548617,
  'CEP ': 44700000.0,
  'CORREIO ELETRÔNICO': 'ECARVALHO936@GMAIL.COM',
  'NOME FANTASIA': 'JACOBINA 24 HORAS',
  'TELEFONE': '74.099125102.0'},
 {'CNPJ COMPLETO': 20228531143,
  'CEP ': 71215222.0,
  'CORREIO ELETRÔNICO': 'None',
  'NOME FANTASIA': 'ALSACIA',
  'TELEFONE': '61.033620739.0'},
 {'CNPJ COMPLETO': 2135338217,
  'CEP ': 30580002.0,
  'CORREIO ELETRÔNICO': 'None',
  'NOME FANTASIA': 'IOIO MODA FEMININA PLUS SIZE',
  'TELEFONE': '31.099016151.0'},
 {'CNPJ COMPLETO': 2808635619,
  'CEP ': 15110000.0,
  'CORREIO ELETRÔNICO': 'wellingtonbrandao_@hotmail.com',
  'NOME FANTASIA': 'LIMA TRANSPORTES',
  'TELEFONE': '17.081356928.0'},
 {'CNPJ COMPLETO': 28128189111,
  'CEP ': 29017020.0,
  'CORREIO ELETRÔNICO': 'None',
  'NOME FANTASIA': 'BELTEC',
  'TELEFONE': 'nannan'},
 {'CNPJ COMPLETO': 18884972151,
  'CEP ': 24800037.0,
  'CORREIO ELETRÔNICO': 'None',
  'NOME FANTASIA': 'URBAN SERVICE',
  'TELEFONE': '21.026352295.0'}]

# PyMongo

In [11]:
### Importando bibliotecas para conexão com o MongoDB

import pymongo
import json

In [12]:
### Conectando ao MongoDB

client = pymongo.MongoClient('mongodb://mongoadmin:password@localhost:27017/')
db = client['estabelecimentos']
print(db)

Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'estabelecimentos')

In [13]:
### Inserindo dados no MongoDB

db.dados.insert_many(estabelecimentos_data)

# Elastic Search

In [22]:
### Importando bibliotecas para conexão com o Elasticsearch

import elasticsearch
print(elasticsearch.__version__)

(7, 17, 9)

In [23]:
### Conectando ao Elasticsearch

es = elasticsearch.Elasticsearch([{'host': 'localhost', 'port': 9200}])
resp = es.info()

In [29]:
### Inserindo dados no Elasticsearch

estabelecimentos_data = df.to_dict(orient = "records")
for data in estabelecimentos_data: 
  es.index(index='estabelecimentos', document=data)

In [30]:
### Buscando dados no Elasticsearch

res = es.search(index="estabelecimentos", body={"query": {"match_all": {}}})
print("Got %d Hits:" % res['hits']['total']['value'])

for hit in res['hits']['hits']:
    print("%(CNPJ COMPLETO)s %(NOME FANTASIA)s: %(TELEFONE)s" % hit["_source"])

Got 100 Hits:
23552968126 AILUS: 61.096848374.0
7305415112 BOMBONIERE NOSSA SENHORA DE FATIMA: nannan
4214973910 FRANCO REPRESENTACOES: 45.099287610.0
49527508131 BODY FITNESS COMERCIO DE SUPLEMENTOS E ROUPAS: 34.099364293
4320548617 JACOBINA 24 HORAS: 74.099125102.0
20228531143 ALSACIA: 61.033620739.0
2135338217 IOIO MODA FEMININA PLUS SIZE: 31.099016151.0
2808635619 LIMA TRANSPORTES: 17.081356928.0
28128189111 BELTEC: nannan
18884972151 URBAN SERVICE: 21.026352295.0

C:\Users\lgmot\AppData\Local\Temp\ipykernel_27180\4076193532.py:3: DeprecationWarning: The 'body' parameter is deprecated for the 'search' API and will be removed in a future version. Instead use API parameters directly. See https://github.com/elastic/elasticsearch-py/issues/1698 for more information
  res = es.search(index="estabelecimentos", body={"query": {"match_all": {}}})